name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  conda:
    name: Conda ${{ matrix.python-version }} - ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.9', '3.10', '3.11', '3.12']
        # test oldest and newest libspatialindex versions
        sidx-version: ['1.8.5', '2.0.0']
        exclude:
          - os: 'macos-latest'
          - sidx-version: '1.8.5'

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        channels: conda-forge
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Setup
      run: conda install -c conda-forge numpy pytest libspatialindex=${{ matrix.sidx-version }} -y

    - name: Install
      run: pip install -e .

    - name: Test with pytest
      run: pytest --import-mode=importlib -Werror -v --doctest-modules rtree tests

  ubuntu:
    name: Ubuntu Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Setup
      run: |
          sudo apt-get -y install libspatialindex-c6
          pip install --upgrade pip
          pip install numpy pytest

    - name: Build
      run: pip install --user .

    - name: Test with pytest
      run: pytest --import-mode=importlib -Werror -v --doctest-modules rtree tests
